//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_16_Ladonina.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int id { get; set; }
        public decimal Cena { get; set; }
        public string Naimen { get; set; }
        public int Kol { get; set; }
    }
}
